version: "3"

services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # Default debugging port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres//postgres@database/backend_dev
      PORT: 8000

  database:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: backend_dev
      POSTGRES_HOST_AUTH_METHOD: trust
